### ISSUE TITLE
Not playing to channels. 

### ISSUE THREAD

**Issue by Tracker997** [Chris230291/Docker-STB-Proxy#1]
Hello i'm install this script and add my URL and MAC and generate /playlist.
I'm add this playlist to VLC but not work the channels :(

**Comment by Chris230291** [comment]
The playlist loads but channels no play?
Did you set ` -e HOST=<docker host ip>:<docker host port>`? This is important for it to work.

**Comment by Tracker997** [comment]
Works!!! 
Thank you!!! :)
