### ISSUE TITLE
Session refresh

### ISSUE THREAD

**Issue by kettenbach-it** [Chris230291/Docker-STB-Proxy#7]
Stalkerhek has a watchdog, that calls a certain portal url every two minutes.

See here: https://github.com/erkexzcx/stalkerhek/blob/956d05445094d73115c102f8c38e1587fa74086e/stalker/stalker.go#L32

Is this needed? Will we ween that, too?

**Comment by Chris230291** [comment]
Not sure if that is needed. I think that might be more for real boxes to update statistics or something maybe?
I have been using the main branch of this since release without any problems. But as we know, some portals are funny.

**Comment by kettenbach-it** [comment]
Ok, thx!
